#!/bin/bash
set -e

# Set environment variables
ETCD_ENVIRONMENT_VARIABLE_REGEX="^\s*ETCD2ENV_([^=]+)=(.+)\s*$"
ENV_FILE=$1

# Make sure an output environment file was provided
if [ -z "${ENV_FILE}" ]; then
  echo "You must supply the output environment file as the first argument."
  exit 1
fi

# Build a combined environment file for use in systemd services
mkdir -p "`dirname ${ENV_FILE}`"
cat << EOF > "${ENV_FILE}"
# This environment file is generated by the etcd2env script and
# will be overwritten each time it is run
EOF
while read -r env_name etcd_key ; do
  env_value=$(etcdctl get "${etcd_key}")
  if [ -z "${env_value}" ]; then
    echo >&2 "Unable to get value for '${etcd_key}' from etcd."
  else
    echo "Retrieved value for '${etcd_key}' from etcd."
    echo "${env_name}=${env_value}" >> "${ENV_FILE}"
  fi
done < <(env | grep -E "${ETCD_ENVIRONMENT_VARIABLE_REGEX}"  | sort | sed -E "s/${ETCD_ENVIRONMENT_VARIABLE_REGEX}/\1\t\2/")
